// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Price representa um snapshot de preço de criptomoeda
type Price struct {
	Symbol    string  `json:"symbol"`
	PriceUSD  float64 `json:"priceUSD"`
	Source    string  `json:"source"`
	Timestamp string  `json:"timestamp"`
}

